trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  environmentName: 'test-environment'

stages:
- stage: CreateTestEnvironment
  displayName: 'Create New Testing Environment'
  jobs:
  - job: DeployInfrastructure
    displayName: 'Deploy Test Environment Infrastructure'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Creating new environment: $(environmentName)"
          az group create --name $(environmentName) --location eastus
          az deployment group create --resource-group $(environmentName) --template-file azuredeploy.json --parameters @azuredeploy.parameters.json
      displayName: 'Deploy ARM Template'
  
  - job: DeployApp
    displayName: 'Deploy Application to Test Environment'
    dependsOn: DeployInfrastructure
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Deploying application to $(environmentName)"
          # Add your application deployment steps here
      displayName: 'Deploy Application'

- stage: CleanUp
  displayName: 'Clean Up Test Environment'
  condition: failed()
  jobs:
  - job: DeleteEnvironment
    displayName: 'Delete Test Environment'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Deleting environment: $(environmentName)"
          az group delete --name $(environmentName) --yes --no-wait
      displayName: 'Delete Test Environment'