trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  - name: environmentName
    value: 'dev-$(Build.BuildId)'

stages:
- stage: CreatePowerPlatformEnvironment
  displayName: 'Create Power Platform Environment'
  jobs:
  - job: CreateEnv
    displayName: 'Create Environment'
    steps:
    - task: PowerPlatformToolInstaller@2
      inputs:
        DefaultVersion: true


    - task: PowerPlatformCreateEnvironment@2
      inputs:
        authenticationType: 'PowerPlatformSPN'
        PowerPlatformSPN: 'PowerPlatformConnection'
        DisplayName: '$(environmentName)'
        EnvironmentSku: 'Sandbox'
        LocationName: 'unitedstates'
        LanguageName: 'English'
        CurrencyName: 'USD'
        DomainName: '$(environmentName)'


- stage: ConfigureEnvironment
  displayName: 'Configure Environment'
  dependsOn: CreatePowerPlatformEnvironment
  jobs:
  - job: ConfigureEnv
    displayName: 'Configure Environment'
    steps:
    - task: PowerPlatformToolInstaller@2
      inputs:
        DefaultVersion: true

    - task: PowerPlatformImportSolution@2
      inputs:
        authenticationType: 'PowerPlatformSPN'
        PowerPlatformSPN: 'PowerPlatformConnection'
        Environment: '$(environmentName)'
        SolutionInputFile: '$(Build.SourcesDirectory)/YourSolutionFile.zip'
        AsyncOperation: false
        MaxAsyncWaitTime: '60'
