trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  PowerPlatformUsername: $(PowerPlatformUsername)
  PowerPlatformPassword: $(PowerPlatformPassword)

steps:
- task: PowerShell@2
  displayName: 'Authenticate and Create Power Platform Environment'
  inputs:
    targetType: 'inline'
    script: |
      # Power Platform Authentication using username and password
      $username = $(PowerPlatformUsername)  # Retrieved from pipeline variables
      $securePassword = ConvertTo-SecureString $(PowerPlatformPassword) -AsPlainText -Force
      $cred = New-Object System.Management.Automation.PSCredential ($username, $securePassword)

      # Authenticate Power Apps account
      Add-PowerAppsAccount -Endpoint prod -Credential $cred

      # Example action: Create Power Platform environment
      New-AdminPowerAppEnvironment -EnvironmentName 'TxDOTDev' -Location 'United States' -Type 'Sandbox'