trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  DEV_ENV: 'DEV'
  TEST_ENV: 'TEST'

jobs:
- job: CreateTestEnvironment
  displayName: 'Create TEST Environment'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'MyAzureConnection'  # Replace with your actual Azure service connection
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Creating TEST environment from DEV environment"
        az login
        az group create --name ${TEST_ENV} --location eastus
        az deployment group create --resource-group ${TEST_ENV} --template-file azuredeploy.json
