trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  DEV_ENV: 'DEV'
  TEST_ENV: 'TEST'

jobs:
- job: CreateTestEnvironment
  displayName: 'Create TEST Environment'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      echo "Creating TEST environment from DEV environment"
      # Add your script or commands to create the TEST environment here
      # For example, you might use Azure CLI commands to create resources
      az group create --name $(TEST_ENV) --location eastus
      az group deployment create --resource-group $(TEST_ENV) --template-file azuredeploy.json
    displayName: 'Create TEST Environment'
